name: Infrastructure Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Terraform settings
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID:       ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET:   ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_TENANT_ID:       ${{ secrets.AZURE_AD_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -var-file=terraform.tfvars -out=plan.out

      - name: Terraform apply
        run: terraform apply -auto-approve plan.out
		
